feat: add page example template
ice-lab/material-templates pull request #24
Opened 2020-08-17 14:02 UTC by sspku-yqLiu

2020-08-20 03:25 UTC, alvinhui commented
这个实现的思路有问题。

目前 packages 下的 template 是以物料源为维度来实现的，而不是物料粒度。

应该将 page 的 template 添加到

- template-react
- template-react-ts

2020-08-20 03:29 UTC, alvinhui commented on packages/template-page-example/template/page/build.json
> +    "build-plugin-template"
看起来目前调试构建能力是通过单个插件来实现的，那么未来，如果我需要给 block 也添加配置化能力，如何实现？

2020-08-20 03:31 UTC, alvinhui commented on packages/template-page-example/template/page/config/mock.js
> +module.exports= {
template 还是要简单一些，不需要那么多字段吧。

建议只有：

- isShowUser
- title
- userTitle

2020-08-20 03:32 UTC, alvinhui commented on packages/template-page-example/template/page/package.json.ejs
> +  "description": "page-beta-template",
这里应该也是一个模板变量

2020-08-20 03:32 UTC, alvinhui commented on packages/template-page-example/template/page/package.json.ejs
> +}
参考 https://github.com/ice-lab/material-templates/blob/master/packages/template-react-ts/template/block/package.json.ejs

2020-08-20 03:33 UTC, alvinhui commented on packages/template-page-example/template/page/package.json.ejs
> +  "dependencies": {
不使用的字段删除掉

2020-08-20 03:34 UTC, alvinhui commented on packages/template-page-example/template/page/package.json.ejs
> +  },
缺少 build-plugin-template ，另外 build-plugin-block 不需要。

2020-08-20 03:36 UTC, alvinhui commented
reviewed，细节问题再自查一下，避免在 PR 中有明显的细节错误。

2020-08-20 04:21 UTC, sspku-yqLiu commented on packages/template-page-example/template/page/build.json
> +    "build-plugin-template"
删掉  build-plugin-block 使用 build-plugin-template 即可。
其实 build-plugin-template 是包含了 build-plugin-block 的所有能力的 ，但是因为其添加了 「将内容编译到 .tmp 文件夹下」 如果其不是 ejs 模板，则就是单纯的复制，可能会造成冗余。
如果时间充足的话，我尝试把它们合成一个插件哈。

2020-08-20 06:03 UTC, alvinhui commented on packages/template-page-example/template/page/config/mock.js
> +module.exports= {
预留这三个变量的目的是：

- isShowUser 用来演示加载组件
- title 用来演示入口文件使用模板变量
- userTitle 用来演示组件文件使用模板变量

2020-08-20 06:06 UTC, alvinhui commented on packages/template-page-example/template/page/build.json
> +    "build-plugin-template"
![image](https://user-images.githubusercontent.com/4392234/90722783-0f006780-e2ee-11ea-9b48-1a86738bf3a1.png)

如果是这样的话，应该使用方案 1 ，在 build-plugin-block 里面新增参数。然后使用的时候在 build.json 里指定使用模板方案：

```json
{
	"plugins": [
		[
			"build-plugin-block",
			{
				"usingTemplate": true
			}
		]
	]
}
```

2020-08-20 06:07 UTC, alvinhui commented
第二轮 review 完成，请检查未关闭的评论。

2020-08-20 06:15 UTC, sspku-yqLiu commented on packages/template-page-example/template/page/build.json
> +    "build-plugin-template"
好的 我尝试 merge 一下。
那么这个插件叫什么名字嘞...
build-plugin-block 和 build -plugin-template  似乎都不能准确的描述这个插件的功能

2020-08-20 06:17 UTC, alvinhui commented on packages/template-page-example/template/page/build.json
> +    "build-plugin-template"
就在 build-plugin-block 上新增这种能力。

2020-08-20 06:44 UTC, sspku-yqLiu commented
第二轮修改已经完成， 请查收

2020-08-20 07:25 UTC, alvinhui commented
react-template
react-template-ts

这两个包的版本号需要更新一下

2020-08-20 07:34 UTC, alvinhui approved these changes

2020-08-20 07:34 UTC, alvinhui commented
CC @imsobear

2020-08-20 11:56 UTC, imsobear requested changes

2020-08-20 11:56 UTC, imsobear commented on packages/template-react-ts/template/page/build.json
> +        "materialType":"page"
格式问题

2020-08-20 11:56 UTC, imsobear commented on packages/template-react-ts/template/page/build.json
> +        "materialType":"page"
block 放在第一个

2020-08-20 13:14 UTC, alvinhui commented on packages/template-react/template/page/build.json
> +    ["build-plugin-block",
这个代码风格参考一下第 10 行代码

2020-08-20 13:52 UTC, sspku-yqLiu commented on packages/template-react/template/page/build.json
> +    ["build-plugin-block",
已完成

2020-08-21 02:44 UTC, alvinhui commented
注意页面物料模板后缀应该是 xxx.extname.ejs._ejs/

2020-08-21 06:38 UTC, merged